# Generated by Django 6.0.8 on 2026-09-05 09:38

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InferredEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('table_slug', models.SlugField(max_length=63)),
                ('confidence', models.FloatField(default=0.0)),
                ('user_confirmed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('sheet_index', models.IntegerField()),
                ('detected_header_row', models.IntegerField(blank=True, null=True)),
                ('detected_range', models.CharField(blank=True, default='', max_length=50)),
                ('raw_row_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['sheet_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InferredField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('column_slug', models.SlugField(max_length=63)),
                ('source_column_letter', models.CharField(blank=True, default='', max_length=10)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('numeric', 'Numeric'), ('date', 'Date'), ('datetime', 'Datetime'), ('boolean', 'Boolean'), ('json', 'JSON')], default='text', max_length=20)),
                ('nullable', models.BooleanField(default=True)),
                ('is_primary_key', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0.0)),
                ('user_confirmed', models.BooleanField(default=False)),
                ('sample_values', models.JSONField(default=list)),
                ('position', models.IntegerField(default=0)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='core.inferredentity')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InferredRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('cardinality', models.CharField(choices=[('one_to_many', 'One to many'), ('many_to_one', 'Many to one'), ('one_to_one', 'One to one')], default='many_to_one', max_length=20)),
                ('match_rate', models.FloatField(default=0.0)),
                ('confidence', models.FloatField(default=0.0)),
                ('user_confirmed', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('rationale', models.TextField(blank=True, default='')),
                ('from_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='core.inferredentity')),
                ('from_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='core.inferredfield')),
                ('to_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='core.inferredentity')),
                ('to_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='core.inferredfield')),
            ],
            options={
                'ordering': ['-match_rate', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('source_row_index', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.inferredentity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.organization')),
            ],
            options={
                'db_table': 'record',
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='core.inferredrelationship')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='core.organization')),
                ('from_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='core.record')),
                ('to_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='core.record')),
            ],
            options={
                'db_table': 'edge',
            },
        ),
        migrations.AddField(
            model_name='inferredentity',
            name='source_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='core.sheet'),
        ),
        migrations.CreateModel(
            name='Workbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='workbooks/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('analysing', 'Analysing'), ('proposed', 'Proposed'), ('committed', 'Committed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workbooks', to='core.organization')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='sheet',
            name='workbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='core.workbook'),
        ),
        migrations.AddField(
            model_name='inferredrelationship',
            name='workbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='core.workbook'),
        ),
        migrations.AddField(
            model_name='inferredentity',
            name='workbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='core.workbook'),
        ),
        migrations.AddConstraint(
            model_name='inferredfield',
            constraint=models.UniqueConstraint(fields=('entity', 'column_slug'), name='uniq_field_slug_per_entity'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=django.contrib.postgres.indexes.GinIndex(fields=['data'], name='record_data_gin'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['entity'], name='record_entity_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['organization'], name='record_org_idx'),
        ),
        migrations.AddIndex(
            model_name='edge',
            index=models.Index(fields=['from_record'], name='edge_from_idx'),
        ),
        migrations.AddIndex(
            model_name='edge',
            index=models.Index(fields=['to_record'], name='edge_to_idx'),
        ),
        migrations.AddIndex(
            model_name='edge',
            index=models.Index(fields=['organization'], name='edge_org_idx'),
        ),
        migrations.AddConstraint(
            model_name='inferredrelationship',
            constraint=models.UniqueConstraint(fields=('from_field', 'to_field'), name='uniq_relationship_field_pair'),
        ),
        migrations.AddConstraint(
            model_name='inferredentity',
            constraint=models.UniqueConstraint(fields=('workbook', 'table_slug'), name='uniq_entity_slug_per_workbook'),
        ),
    ]
