# Generated by Django 6.0.8 on 2026-09-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferredfield',
            name='source_header',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
