# Generated by Django 6.0.8 on 2026-09-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_inferredfield_source_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferredrelationship',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
    ]
