# Generated by Django 6.0.8 on 2026-09-08 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_inferredrelationship_needs_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntitySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('note', 'Note'), ('summary', 'Summary'), ('meta', 'Meta')], default='note', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('body', models.TextField(blank=True, default='')),
                ('source_range', models.CharField(blank=True, default='', max_length=50)),
                ('position', models.IntegerField(default=0)),
                ('created_by_user', models.BooleanField(default=False)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.inferredentity')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
